//Nome: Erick Elsas de Freitas - RA: 2347938 - Engenharia de Software
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CadEnf extends javax.swing.JFrame {
    private static CadEnf unicoCadEnf;   
    private Enfermeiro enf = new Enfermeiro();
    private static BD_Enf bdEnf = new BD_Enf();
    /**
     * Creates new form MenuMed
     */
    public static CadEnf getCadEnf(){
        if(unicoCadEnf == null){
            unicoCadEnf = new CadEnf();
        }
        return unicoCadEnf;
    }
    public CadEnf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cxEstado = new javax.swing.JTextField();
        labelTel = new javax.swing.JLabel();
        labelEmprego = new javax.swing.JLabel();
        cxCidade = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        cxNumCasa = new javax.swing.JTextField();
        labelEndereco = new javax.swing.JLabel();
        cxCtps = new javax.swing.JTextField();
        labelCompl = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        labelSalario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabEnf = new javax.swing.JTable();
        cxRua = new javax.swing.JTextField();
        btConsultar = new javax.swing.JButton();
        labelPais = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        cxBairro = new javax.swing.JTextField();
        cxMesNasc = new javax.swing.JTextField();
        cxCompl = new javax.swing.JTextField();
        labelEnfermeiro = new javax.swing.JLabel();
        cxSalario = new javax.swing.JTextField();
        labelCtps = new javax.swing.JLabel();
        cxDiaNasc = new javax.swing.JTextField();
        labelDdd = new javax.swing.JLabel();
        Relatório = new javax.swing.JButton();
        cxCpf = new javax.swing.JTextField();
        cxAnoNasc = new javax.swing.JTextField();
        labelSexo = new javax.swing.JLabel();
        cxCep = new javax.swing.JTextField();
        labelCidade = new javax.swing.JLabel();
        labelRg = new javax.swing.JLabel();
        labelBairro = new javax.swing.JLabel();
        btDeletar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        labelDiaNasc = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        cxTel = new javax.swing.JTextField();
        labelTelefone = new javax.swing.JLabel();
        labelNumCasa = new javax.swing.JLabel();
        cxPais = new javax.swing.JTextField();
        cxEmail = new javax.swing.JTextField();
        cxDdd = new javax.swing.JTextField();
        labelAnoNasc = new javax.swing.JLabel();
        labelCep = new javax.swing.JLabel();
        cxSexo = new javax.swing.JTextField();
        labelMesNac = new javax.swing.JLabel();
        btAtualizar = new javax.swing.JButton();
        labelRua = new javax.swing.JLabel();
        cxRg = new javax.swing.JTextField();
        labelGrauForm = new javax.swing.JLabel();
        cxGrauForm = new javax.swing.JTextField();
        labelSetorHosp = new javax.swing.JLabel();
        cxSetorHosp = new javax.swing.JTextField();
        btReajusta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTel.setText("TELEFONE");

        labelEmprego.setText("DADOS EMPREGO");

        labelEmail.setText("EMAIL");

        labelEndereco.setText("ENDEREÇO");

        labelCompl.setText("COMPLEMENTO");

        btCadastrar.setText("CADASTRAR");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btLimpar.setText("LIMPAR");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        labelSalario.setText("SALÁRIO");

        tabEnf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NOME", "CPF", "SETOR"
            }
        ));
        tabEnf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabEnfMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabEnf);

        btConsultar.setText("CONSULTAR");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        labelPais.setText("PAÍS");

        labelCpf.setText("CPF");

        cxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeActionPerformed(evt);
            }
        });

        labelEnfermeiro.setText("DADOS ENFERMEIRO");

        labelCtps.setText("CTPS");

        labelDdd.setText("DDD");

        Relatório.setText("RELATÓRIO");
        Relatório.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatórioActionPerformed(evt);
            }
        });

        labelSexo.setText("SEXO");

        labelCidade.setText("CIDADE");

        labelRg.setText("RG");

        labelBairro.setText("BAIRRO");

        btDeletar.setText("DELETAR");
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });

        btSair.setText("SAIR");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        labelDiaNasc.setText("DIA NASCIMENTO");

        labelEstado.setText("ESTADO");

        labelNome.setText("NOME");

        labelTelefone.setText("TELEFONE");

        labelNumCasa.setText("NÚMERO CASA");

        labelAnoNasc.setText("ANO NASCIMENTO");

        labelCep.setText("CEP");

        labelMesNac.setText("MÊS NASCIMENTO");

        btAtualizar.setText("ATUALIZAR");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        labelRua.setText("RUA");

        labelGrauForm.setText("GRAU DE FORMAÇÃO");

        labelSetorHosp.setText("SETOR HOSPITALAR");

        btReajusta.setText("REAJUSTA");
        btReajusta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReajustaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(labelEmprego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDiaNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxDiaNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelMesNac, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxMesNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelAnoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxAnoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelEnfermeiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(labelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelRua, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxRua, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(labelNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPais, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(labelCep, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxCep, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCtps, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxCtps, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(labelSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(labelCompl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxCompl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(labelDdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxDdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(labelTel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxTel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelRg, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxRg, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelGrauForm, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxGrauForm, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(labelSetorHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxSetorHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Relatório, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btReajusta, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCpf)
                    .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRg)
                    .addComponent(cxRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSexo)
                    .addComponent(cxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMesNac)
                    .addComponent(cxMesNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDiaNasc)
                    .addComponent(cxDiaNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAnoNasc)
                    .addComponent(cxAnoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail)
                    .addComponent(cxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRua)
                    .addComponent(cxRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumCasa)
                    .addComponent(cxNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBairro)
                    .addComponent(cxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCompl)
                    .addComponent(cxCompl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCidade)
                    .addComponent(cxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEstado)
                    .addComponent(cxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPais)
                    .addComponent(cxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCep)
                    .addComponent(cxCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDdd)
                    .addComponent(cxDdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTel)
                    .addComponent(cxTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelEmprego)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCtps)
                    .addComponent(cxCtps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSalario)
                    .addComponent(cxSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelEnfermeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGrauForm)
                    .addComponent(cxGrauForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSetorHosp)
                    .addComponent(cxSetorHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btAtualizar)
                    .addComponent(btLimpar)
                    .addComponent(Relatório, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDeletar)
                    .addComponent(btConsultar)
                    .addComponent(btSair)
                    .addComponent(btReajusta, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        cadEnf();
        listaTab();// TODO add your handling code here:
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();// TODO add your handling code here:
    }//GEN-LAST:event_btLimparActionPerformed

    private void tabEnfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabEnfMouseClicked
        selectTabEnf();        // TODO add your handling code here:
    }//GEN-LAST:event_tabEnfMouseClicked

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consEnfCpf();        // TODO add your handling code here:
    }//GEN-LAST:event_btConsultarActionPerformed

    private void cxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeActionPerformed

    private void RelatórioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatórioActionPerformed
        abrirRelatorio();        // TODO add your handling code here:
    }//GEN-LAST:event_RelatórioActionPerformed

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        excluiEnfCpf();
        listaTab();// TODO add your handling code here:
    }//GEN-LAST:event_btDeletarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();        // TODO add your handling code here:
    }//GEN-LAST:event_btSairActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        atualizaEnfCpf();        // TODO add your handling code here:
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btReajustaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReajustaActionPerformed
        reajusta();        // TODO add your handling code here:
    }//GEN-LAST:event_btReajustaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadEnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadEnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadEnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadEnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadEnf().setVisible(true);
            }
        });
    }
    
    public void abrirRelatorio(){
        RelBDEnf.getRelBDEnf(bdEnf).setVisible(true);
    }
    
    public void selectTabEnf(){
        String valLinTab = "";
        int posLin = tabEnf.getSelectedRow();
          
        
        for(int coluna = 0;coluna < tabEnf.getColumnCount(); coluna++ ){
            valLinTab += tabEnf.getModel().getValueAt(posLin,coluna).toString();
            
            if(coluna < tabEnf.getColumnCount()-1){
               valLinTab += " - ";
            }
            
            
        }
        JOptionPane.showMessageDialog(
                null,
                "Valor escolhido: "+ valLinTab,
                "Seleção na tabela",
                1
        );
    }
        
    public void listaTab(){
        DefaultTableModel modelo = (DefaultTableModel) tabEnf.getModel();
        
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for(Enfermeiro enf : bdEnf.getBdEnf() ){
            modelo.insertRow(posLin, new Object[]{enf.getNome(), enf.getCpf(), enf.getSetorHosp()});
            posLin++;
        }
    }
        
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                    null,
                    "Deseja sair?",
                    "Saida",
                    JOptionPane.YES_NO_OPTION
                  );
        if(resp == 0){
            dispose();
        }
    }

    public void limpar(){
        cxNome.setText("");
        cxCpf.setText("");
        cxSexo.setText("");
        cxRg.setText("");
        cxDiaNasc.setText("");
        cxMesNasc.setText("");
        cxAnoNasc.setText("");
        cxRua.setText("");
        cxNumCasa.setText("");
        cxCompl.setText("");
        cxBairro.setText("");
        cxEstado.setText("");
        cxCidade.setText("");
        cxPais.setText("");
        cxCep.setText("");
        cxDdd.setText("");
        cxTel.setText("");
        cxCtps.setText("");
        cxSalario.setText("");
        cxGrauForm.setText("");
        cxSetorHosp.setText("");
        cxEmail.setText("");
        cxNome.requestFocus();
    }
    
    public void cadEnf(){
       enf = new Enfermeiro();
       int flag = 1;
       
       try{
           enf.setCpf(cxCpf.getText());
           enf.setNome(cxNome.getText());
           enf.setSexo(cxSexo.getText().charAt(0));
           enf.setRg(cxRg.getText());
           enf.setEmail(cxEmail.getText());
           enf.getDataNasc().setDia(Integer.parseInt(cxDiaNasc.getText()));
           enf.getDataNasc().setMes(Integer.parseInt(cxMesNasc.getText()));
           enf.getDataNasc().setAno(Integer.parseInt(cxAnoNasc.getText()));
           enf.getEnd().setNome(cxRua.getText());
           enf.getEnd().setNum(Integer.parseInt(cxNumCasa.getText()));
           enf.getEnd().setBairro(cxBairro.getText());
           enf.getEnd().setCompl(cxCompl.getText());
           enf.getEnd().setCidade(cxCidade.getText());
           enf.getEnd().setEstado(cxEstado.getText());
           enf.getEnd().setPais(cxPais.getText());
           enf.getEnd().setCep(Integer.parseInt(cxCep.getText()));
           enf.getTel().setDdd(Integer.parseInt(cxDdd.getText()));
           enf.getTel().setTel(Integer.parseInt(cxTel.getText()));
           enf.setSalario(Float.parseFloat(cxSalario.getText()));
           enf.setCtps(Integer.parseInt(cxCtps.getText()));
           enf.setGrauForm(cxGrauForm.getText());
           enf.setSetorHosp(cxSetorHosp.getText());
           flag = 0;
       } catch (CpfTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "CPF deve ter 11 números!", "Erro!", 0);
        } catch (SexoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, "Sexo deve ser F ou M!", "Erro!", 0);
        } catch (RgTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "RG deve ter 9 números!!", "Erro!", 0);
        } catch (DiaInvalidoException ex) {
            JOptionPane.showMessageDialog(null, "Dia deve ser um valor entre 1 e 31!", "Erro!", 0);
        } catch (MesInvalidoException ex) {
            JOptionPane.showMessageDialog(null, "Mês deve ser um valor entre 1 e 12!", "Erro!", 0);
        } catch (AnoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, "Ano deve ser um valor entre 1900 e 2022", "Erro!", 0);
        } catch (NumNegException ex) {
            JOptionPane.showMessageDialog(null, "Rua deve ter um valor positivo!", "Erro!", 0);
        } catch (EstadoTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "Estado deve ter dois caracteres!", "Erro!", 0);
        } catch (EstadoCaracterException ex) {
            JOptionPane.showMessageDialog(null, "Estado deve ser composto por letras!", "Erro!", 0);
        } catch (CepTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "CEP deve ter 9 números!", "Erro!", 0);
        } catch (DddTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "DDD deve ter 2 números!", "Erro!", 0);
        } catch (TelefoneTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "Telefone deve ter 9 números!", "Erro!", 0);
        } catch (SalarioMinException ex) {
            JOptionPane.showMessageDialog(null, "Salário deve ser um valor maior que R$1212", "Erro!", 0);
        } catch (CtpsTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "CTPS deve ter 8 algorismos", "Erro!", 0);
        } catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Data de Nascimento, número da rua, CEP, CTPS ou CRM devem ser compostos por números", "Erro!", 0);
        }
       
       if(flag == 0){
           enf = bdEnf.cadEnf(enf);
       } else {
           JOptionPane.showMessageDialog(null,
                   "Erro durante cadastro! Tente Novamente",
                   "Erro de cadastro", 0);
           return;
       }

       if(enf != null){
                JOptionPane.showMessageDialog(
                    null,
                    "Enfermeiro cadastrado com sucesso!",
                    "Cadastro Ok",
                    1
                );
                limpar();
       }
       else{
                JOptionPane.showMessageDialog(
                    null,
                    "Já existe uma pessoa com este CPF ou CRM",
                    "Erro de Cadastro",
                    0
                );
                limpar();
       }
    }
       
    public void excluiEnfCpf(){
      enf = new Enfermeiro();
      
      try{
          enf.setCpf(cxCpf.getText());
      } catch(CpfTamanhoException cte){
          JOptionPane.showMessageDialog(null, "CPF deve ter 11 números!", "Erro!", 0);
      }
      
      enf = bdEnf.removeEnfCod(enf);
       
      if(enf == null){
            JOptionPane.showMessageDialog(
                    null,
                    "Pessoa EXCLUÍDA com sucesso!",
                    "Exclusão OK",
                    1
                );
      }
      else{
                  JOptionPane.showMessageDialog(
                    null,
                    "Não existe uma pessoa com este CPF",
                    "Erro de Excluasão",
                    0
                );
               
      }
      limpar();
    }
    
     public void atualizaEnfCpf(){
      enf = new Enfermeiro();
      
      try{
          enf.setCpf(cxCpf.getText());
      } catch(CpfTamanhoException cte){
          JOptionPane.showMessageDialog(null, "CPF deve ter 11 números!", "Erro!", 0);
      }
      
      enf = bdEnf.atualizaEnfCod(enf);    
       
      if(enf != null){
        cxNome.setText(enf.getNome());
        cxCpf.setText(enf.getCpf());
        cxSexo.setText(Character.toString(enf.getSexo()));
        cxRg.setText(enf.getRg());
        cxDiaNasc.setText(Integer.toString(enf.getDataNasc().getDia()));
        cxMesNasc.setText(Integer.toString(enf.getDataNasc().getMes()));
        cxAnoNasc.setText(Integer.toString(enf.getDataNasc().getAno()));
        cxRua.setText(enf.getEnd().getNome());
        cxNumCasa.setText(Integer.toString(enf.getEnd().getNum()));
        cxCompl.setText(enf.getEnd().getCompl());
        cxBairro.setText(enf.getEnd().getBairro());
        cxEstado.setText(enf.getEnd().getEstado());
        cxCidade.setText(enf.getEnd().getCidade());
        cxPais.setText(enf.getEnd().getPais());
        cxCep.setText(Integer.toString(enf.getEnd().getCep()));
        cxDdd.setText(Integer.toString(enf.getTel().getDdd()));
        cxTel.setText(Integer.toString(enf.getTel().getTel()));
        cxCtps.setText(Integer.toString(enf.getCtps()));
        cxSalario.setText(Float.toString(enf.getSalario()));
        cxGrauForm.setText(enf.getGrauForm());
        cxSetorHosp.setText(enf.getSetorHosp());
                JOptionPane.showMessageDialog(
                    null,
                    "Pessoa atualizada com sucesso!",
                    "Atualização OK",
                    1
                );
      }
      else{
                  JOptionPane.showMessageDialog(
                    null,
                    "Não existe uma pessoa com este CPF",
                    "Erro de Alteração",
                    0
                );
               
      }
      limpar();
    }
     
   public void consEnfCpf(){
      enf = new Enfermeiro();
      
      try{
          enf.setCpf(cxCpf.getText());
      } catch(CpfTamanhoException cte){
          JOptionPane.showMessageDialog(null, "CPF deve ter 11 números!", "Erro!", 0);
      }
    
      enf = bdEnf.consEnfCod(enf);    

       
      if(enf != null){
        cxNome.setText(enf.getNome());
        cxCpf.setText(enf.getCpf());
        cxSexo.setText(Character.toString(enf.getSexo()));
        cxRg.setText(enf.getRg());
        cxDiaNasc.setText(Integer.toString(enf.getDataNasc().getDia()));
        cxMesNasc.setText(Integer.toString(enf.getDataNasc().getMes()));
        cxAnoNasc.setText(Integer.toString(enf.getDataNasc().getAno()));
        cxRua.setText(enf.getEnd().getNome());
        cxNumCasa.setText(Integer.toString(enf.getEnd().getNum()));
        cxCompl.setText(enf.getEnd().getCompl());
        cxBairro.setText(enf.getEnd().getBairro());
        cxEstado.setText(enf.getEnd().getEstado());
        cxCidade.setText(enf.getEnd().getCidade());
        cxPais.setText(enf.getEnd().getPais());
        cxCep.setText(Integer.toString(enf.getEnd().getCep()));
        cxDdd.setText(Integer.toString(enf.getTel().getDdd()));
        cxTel.setText(Integer.toString(enf.getTel().getTel()));
        cxCtps.setText(Integer.toString(enf.getCtps()));
        cxSalario.setText(Float.toString(enf.getSalario()));
        cxGrauForm.setText(enf.getGrauForm());
        cxSetorHosp.setText(enf.getSetorHosp());
        cxEmail.setText(enf.getEmail());
      }
      else{
                  JOptionPane.showMessageDialog(
                    null,
                    "Não existe uma pessoa com este CPF",
                    "Erro de Consulta",
                    0
                );
                limpar();
      }
        
    }
   
    public void reajusta(){
      enf = new Enfermeiro();
      
      try{
          enf.setCpf(cxCpf.getText());
      } catch(CpfTamanhoException cte){
          JOptionPane.showMessageDialog(null, "CPF deve ter 11 números!", "Erro!", 0);
      }
    
      enf = bdEnf.reajustaEnf(enf);    

      consEnfCpf();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Relatório;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btReajusta;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxAnoNasc;
    private javax.swing.JTextField cxBairro;
    private javax.swing.JTextField cxCep;
    private javax.swing.JTextField cxCidade;
    private javax.swing.JTextField cxCompl;
    private javax.swing.JTextField cxCpf;
    private javax.swing.JTextField cxCtps;
    private javax.swing.JTextField cxDdd;
    private javax.swing.JTextField cxDiaNasc;
    private javax.swing.JTextField cxEmail;
    private javax.swing.JTextField cxEstado;
    private javax.swing.JTextField cxGrauForm;
    private javax.swing.JTextField cxMesNasc;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxNumCasa;
    private javax.swing.JTextField cxPais;
    private javax.swing.JTextField cxRg;
    private javax.swing.JTextField cxRua;
    private javax.swing.JTextField cxSalario;
    private javax.swing.JTextField cxSetorHosp;
    private javax.swing.JTextField cxSexo;
    private javax.swing.JTextField cxTel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAnoNasc;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCep;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelCompl;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelCtps;
    private javax.swing.JLabel labelDdd;
    private javax.swing.JLabel labelDiaNasc;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmprego;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelEnfermeiro;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelGrauForm;
    private javax.swing.JLabel labelMesNac;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumCasa;
    private javax.swing.JLabel labelPais;
    private javax.swing.JLabel labelRg;
    private javax.swing.JLabel labelRua;
    private javax.swing.JLabel labelSalario;
    private javax.swing.JLabel labelSetorHosp;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel labelTel;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JTable tabEnf;
    // End of variables declaration//GEN-END:variables
}
