//Nome: Erick Elsas de Freitas - RA: 2347938 - Engenharia de Software
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CadMed extends javax.swing.JFrame {
    private static CadMed unicoCadMed;   
    private Medico med = new Medico();
    private static BD_Med bdMed = new BD_Med();
    /**
     * Creates new form MenuMed
     */
    public static CadMed getCadMed(){
        if(unicoCadMed == null){
            unicoCadMed = new CadMed();
        }
        return unicoCadMed;
    }
        
    public CadMed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        labelCpf = new javax.swing.JLabel();
        cxCpf = new javax.swing.JTextField();
        labelRg = new javax.swing.JLabel();
        cxRg = new javax.swing.JTextField();
        labelEndereco = new javax.swing.JLabel();
        labelRua = new javax.swing.JLabel();
        cxRua = new javax.swing.JTextField();
        labelNumCasa = new javax.swing.JLabel();
        cxNumCasa = new javax.swing.JTextField();
        labelBairro = new javax.swing.JLabel();
        cxBairro = new javax.swing.JTextField();
        labelCompl = new javax.swing.JLabel();
        cxCompl = new javax.swing.JTextField();
        labelCidade = new javax.swing.JLabel();
        cxCidade = new javax.swing.JTextField();
        labelEstado = new javax.swing.JLabel();
        cxEstado = new javax.swing.JTextField();
        labelPais = new javax.swing.JLabel();
        cxPais = new javax.swing.JTextField();
        labelCep = new javax.swing.JLabel();
        cxCep = new javax.swing.JTextField();
        labelTelefone = new javax.swing.JLabel();
        labelDdd = new javax.swing.JLabel();
        cxDdd = new javax.swing.JTextField();
        labelTel = new javax.swing.JLabel();
        cxTel = new javax.swing.JTextField();
        labelSexo = new javax.swing.JLabel();
        cxSexo = new javax.swing.JTextField();
        labelDiaNasc = new javax.swing.JLabel();
        cxDiaNasc = new javax.swing.JTextField();
        labelMesNac = new javax.swing.JLabel();
        cxMesNasc = new javax.swing.JTextField();
        labelAnoNasc = new javax.swing.JLabel();
        cxAnoNasc = new javax.swing.JTextField();
        labelEmprego = new javax.swing.JLabel();
        labelCtps = new javax.swing.JLabel();
        cxCtps = new javax.swing.JTextField();
        labelSalario = new javax.swing.JLabel();
        cxSalario = new javax.swing.JTextField();
        labelMedico = new javax.swing.JLabel();
        labelCrmNum = new javax.swing.JLabel();
        cxCrmNum = new javax.swing.JTextField();
        labelCrmEstado = new javax.swing.JLabel();
        cxCrmEstado = new javax.swing.JTextField();
        labelEspec = new javax.swing.JLabel();
        cxEspec = new javax.swing.JTextField();
        btDeletar = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        labelEmail = new javax.swing.JLabel();
        cxEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabMed = new javax.swing.JTable();
        Relatório = new javax.swing.JButton();
        Reajusta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelNome.setText("NOME");

        cxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeActionPerformed(evt);
            }
        });

        labelCpf.setText("CPF");

        labelRg.setText("RG");

        labelEndereco.setText("ENDEREÇO");

        labelRua.setText("RUA");

        labelNumCasa.setText("NÚMERO CASA");

        labelBairro.setText("BAIRRO");

        labelCompl.setText("COMPLEMENTO");

        labelCidade.setText("CIDADE");

        labelEstado.setText("ESTADO");

        labelPais.setText("PAÍS");

        labelCep.setText("CEP");

        labelTelefone.setText("TELEFONE");

        labelDdd.setText("DDD");

        labelTel.setText("TELEFONE");

        labelSexo.setText("SEXO");

        labelDiaNasc.setText("DIA NASCIMENTO");

        labelMesNac.setText("MÊS NASCIMENTO");

        labelAnoNasc.setText("ANO NASCIMENTO");

        labelEmprego.setText("DADOS EMPREGO");

        labelCtps.setText("CTPS");

        labelSalario.setText("SALÁRIO");

        labelMedico.setText("DADOS MÉDICO");

        labelCrmNum.setText("CRM - NUMERO");

        labelCrmEstado.setText("CRM -  ESTADO");

        labelEspec.setText("ESPECIALIZAÇÃO");

        btDeletar.setText("DELETAR");
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });

        btCadastrar.setText("CADASTRAR");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btAtualizar.setText("ATUALIZAR");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btConsultar.setText("CONSULTAR");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btLimpar.setText("LIMPAR");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("SAIR");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        labelEmail.setText("EMAIL");

        tabMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NOME", "CPF", "ESPECIALIZAÇÃO"
            }
        ));
        tabMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMedMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabMed);

        Relatório.setText("RELATÓRIO");
        Relatório.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatórioActionPerformed(evt);
            }
        });

        Reajusta.setText("REAJUSTA");
        Reajusta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReajustaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(labelEmprego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDiaNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxDiaNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelMesNac, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxMesNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(labelCompl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxCompl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelDdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxDdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(labelTel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxTel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelRg, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxRg, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelAnoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxAnoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Relatório, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btDeletar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelEspec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cxEspec, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Reajusta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(labelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelRua, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxRua, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(labelNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPais, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(labelCep, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxCep, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCtps, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxCtps, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(labelSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCrmNum, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxCrmNum, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(labelCrmEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxCrmEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCpf)
                    .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRg)
                    .addComponent(cxRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSexo)
                    .addComponent(cxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMesNac)
                    .addComponent(cxMesNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDiaNasc)
                    .addComponent(cxDiaNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAnoNasc)
                    .addComponent(cxAnoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail)
                    .addComponent(cxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRua)
                    .addComponent(cxRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumCasa)
                    .addComponent(cxNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBairro)
                    .addComponent(cxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCompl)
                    .addComponent(cxCompl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCidade)
                    .addComponent(cxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEstado)
                    .addComponent(cxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPais)
                    .addComponent(cxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCep)
                    .addComponent(cxCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDdd)
                    .addComponent(cxDdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTel)
                    .addComponent(cxTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelEmprego)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCtps)
                    .addComponent(cxCtps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSalario)
                    .addComponent(cxSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelMedico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCrmNum)
                    .addComponent(cxCrmNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCrmEstado)
                    .addComponent(cxCrmEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEspec)
                    .addComponent(cxEspec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btAtualizar)
                    .addComponent(btLimpar)
                    .addComponent(Relatório, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDeletar)
                    .addComponent(btConsultar)
                    .addComponent(btSair)
                    .addComponent(Reajusta, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        excluiMedCpf(); 
        listaTab();// TODO add your handling code here:
    }//GEN-LAST:event_btDeletarActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        cadMed();   
        listaTab();// TODO add your handling code here:
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        atualizaMedCpf();        // TODO add your handling code here:
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consMedCpf();        // TODO add your handling code here:
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();// TODO add your handling code here:
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();        // TODO add your handling code here:
    }//GEN-LAST:event_btSairActionPerformed

    private void RelatórioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatórioActionPerformed
        abrirRelatorio();        // TODO add your handling code here:
    }//GEN-LAST:event_RelatórioActionPerformed

    private void tabMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMedMouseClicked
        selectTabMed();        // TODO add your handling code here:
    }//GEN-LAST:event_tabMedMouseClicked

    private void cxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeActionPerformed

    private void ReajustaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReajustaActionPerformed
        reajusta();        // TODO add your handling code here:
    }//GEN-LAST:event_ReajustaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadMed().setVisible(true);
            }
        });
    }
    
    public void abrirRelatorio(){
        RelBDMed.getRelBDMed(bdMed).setVisible(true);
    }
    
    public void selectTabMed(){
        String valLinTab = "";
        int posLin = tabMed.getSelectedRow();
          
        
        for(int coluna = 0;coluna < tabMed.getColumnCount(); coluna++ ){
            valLinTab += tabMed.getModel().getValueAt(posLin,coluna).toString();
            
            if(coluna < tabMed.getColumnCount()-1){
               valLinTab += " - ";
            }
            
        }
        JOptionPane.showMessageDialog(
                null,
                "Valor escolhido: "+ valLinTab,
                "Seleção na tabela",
                1
        );
    }
        
    public void listaTab(){
        DefaultTableModel modelo = (DefaultTableModel) tabMed.getModel();
        
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for(Medico med : bdMed.getBdMed() ){
            modelo.insertRow(posLin, new Object[]{med.getNome(), med.getCpf(), med.getEspec()});
            posLin++;
        }
    }
        
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                    null,
                    "Deseja sair?",
                    "Saida",
                    JOptionPane.YES_NO_OPTION
                  );
        if(resp == 0){
            dispose();
        }
    }

    public void limpar(){
        cxNome.setText("");
        cxCpf.setText("");
        cxSexo.setText("");
        cxRg.setText("");
        cxDiaNasc.setText("");
        cxMesNasc.setText("");
        cxAnoNasc.setText("");
        cxRua.setText("");
        cxNumCasa.setText("");
        cxCompl.setText("");
        cxBairro.setText("");
        cxEstado.setText("");
        cxCidade.setText("");
        cxPais.setText("");
        cxCep.setText("");
        cxDdd.setText("");
        cxTel.setText("");
        cxCtps.setText("");
        cxSalario.setText("");
        cxCrmNum.setText("");
        cxCrmEstado.setText("");
        cxEspec.setText("");
        cxEmail.setText("");
        cxNome.requestFocus();
    }
    
    public void cadMed(){
       med = new Medico();
       int flag = 1;
       
       try{
           med.setCpf(cxCpf.getText());
           med.setNome(cxNome.getText());
           med.setSexo(cxSexo.getText().charAt(0));
           med.setRg(cxRg.getText());
           med.setEmail(cxEmail.getText());
           med.getDataNasc().setDia(Integer.parseInt(cxDiaNasc.getText()));
           med.getDataNasc().setMes(Integer.parseInt(cxMesNasc.getText()));
           med.getDataNasc().setAno(Integer.parseInt(cxAnoNasc.getText()));
           med.getEnd().setNome(cxRua.getText());
           med.getEnd().setNum(Integer.parseInt(cxNumCasa.getText()));
           med.getEnd().setBairro(cxBairro.getText());
           med.getEnd().setCompl(cxCompl.getText());
           med.getEnd().setCidade(cxCidade.getText());
           med.getEnd().setEstado(cxEstado.getText());
           med.getEnd().setPais(cxPais.getText());
           med.getEnd().setCep(Integer.parseInt(cxCep.getText()));
           med.getTel().setDdd(Integer.parseInt(cxDdd.getText()));
           med.getTel().setTel(Integer.parseInt(cxTel.getText()));
           med.setSalario(Float.parseFloat(cxSalario.getText()));
           med.setCtps(Integer.parseInt(cxCtps.getText()));
           med.getCrm().setEstado(cxCrmEstado.getText());
           med.getCrm().setNum(Integer.parseInt(cxCrmNum.getText()));
           med.setEspec(cxEspec.getText());
           flag = 0;
       } catch (CpfTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "CPF deve ter 11 números!", "Erro!", 0);
        } catch (SexoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, "Sexo deve ser F ou M!", "Erro!", 0);
        } catch (RgTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "RG deve ter 9 números!!", "Erro!", 0);
        } catch (DiaInvalidoException ex) {
            JOptionPane.showMessageDialog(null, "Dia deve ser um valor entre 1 e 31!", "Erro!", 0);
        } catch (MesInvalidoException ex) {
            JOptionPane.showMessageDialog(null, "Mês deve ser um valor entre 1 e 12!", "Erro!", 0);
        } catch (AnoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, "Ano deve ser um valor entre 1900 e 2022", "Erro!", 0);
        } catch (NumNegException ex) {
            JOptionPane.showMessageDialog(null, "Rua deve ter um valor positivo!", "Erro!", 0);
        } catch (EstadoTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "Estado deve ter dois caracteres!", "Erro!", 0);
        } catch (EstadoCaracterException ex) {
            JOptionPane.showMessageDialog(null, "Estado deve ser composto por letras!", "Erro!", 0);
        } catch (CepTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "CEP deve ter 9 números!", "Erro!", 0);
        } catch (DddTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "DDD deve ter 2 números!", "Erro!", 0);
        } catch (TelefoneTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "Telefone deve ter 9 números!", "Erro!", 0);
        } catch (SalarioMinException ex) {
            JOptionPane.showMessageDialog(null, "Salário deve ser um valor maior que R$1212", "Erro!", 0);
        } catch (CtpsTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "CTPS deve ter 8 algorismos", "Erro!", 0);
        } catch (CrmTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "CRM deve ser composto por 6 algorismos!", "Erro!", 0);
        } catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Data de Nascimento, número da rua, CEP, CTPS ou CRM devem ser compostos por números", "Erro!", 0);
        }
       
       if(flag == 0){
           med = bdMed.cadMed(med);
       } else {
           JOptionPane.showMessageDialog(null,
                   "Erro durante cadastro! Tente Novamente",
                   "Erro de cadastro", 0);
           return;
       }

       if(med != null){
                JOptionPane.showMessageDialog(
                    null,
                    "Medico cadastrado com sucesso!",
                    "Cadastro Ok",
                    1
                );
                limpar();
       }
       else{
                JOptionPane.showMessageDialog(
                    null,
                    "Já existe uma pessoa com este CPF ou CRM",
                    "Erro de Cadastro",
                    0
                );
                limpar();
       }
    }
       
    public void excluiMedCpf(){
      med = new Medico();
      
      try{
          med.setCpf(cxCpf.getText());
      } catch(CpfTamanhoException cte){
          JOptionPane.showMessageDialog(null, "CPF deve ter 11 números!", "Erro!", 0);
      }
      
      med = bdMed.removeMedCod(med);
       
      if(med == null){
            JOptionPane.showMessageDialog(
                    null,
                    "Pessoa EXCLUÍDA com sucesso!",
                    "Exclusão OK",
                    1
                );
      }
      else{
                  JOptionPane.showMessageDialog(
                    null,
                    "Não existe uma pessoa com este CPF",
                    "Erro de Excluasão",
                    0
                );
               
      }
      limpar();
    }
    
     public void atualizaMedCpf(){
      med = new Medico();
      
      try{
          med.setCpf(cxCpf.getText());
      } catch(CpfTamanhoException cte){
          JOptionPane.showMessageDialog(null, "CPF deve ter 11 números!", "Erro!", 0);
      }
      
      med = bdMed.atualizaMedCod(med);    
       
      if(med != null){
        cxNome.setText(med.getNome());
        cxCpf.setText(med.getCpf());
        cxSexo.setText(Character.toString(med.getSexo()));
        cxRg.setText(med.getRg());
        cxDiaNasc.setText(Integer.toString(med.getDataNasc().getDia()));
        cxMesNasc.setText(Integer.toString(med.getDataNasc().getMes()));
        cxAnoNasc.setText(Integer.toString(med.getDataNasc().getAno()));
        cxRua.setText(med.getEnd().getNome());
        cxNumCasa.setText(Integer.toString(med.getEnd().getNum()));
        cxCompl.setText(med.getEnd().getCompl());
        cxBairro.setText(med.getEnd().getBairro());
        cxEstado.setText(med.getEnd().getEstado());
        cxCidade.setText(med.getEnd().getCidade());
        cxPais.setText(med.getEnd().getPais());
        cxCep.setText(Integer.toString(med.getEnd().getCep()));
        cxDdd.setText(Integer.toString(med.getTel().getDdd()));
        cxTel.setText(Integer.toString(med.getTel().getTel()));
        cxCtps.setText(Integer.toString(med.getCtps()));
        cxSalario.setText(Float.toString(med.getSalario()));
        cxCrmNum.setText(Integer.toString(med.getCrm().getNum()));
        cxCrmEstado.setText(med.getCrm().getEstado());
        cxEspec.setText(med.getEspec());
        
                JOptionPane.showMessageDialog(
                    null,
                    "Pessoa atualizada com sucesso!",
                    "Atualização OK",
                    1
                );
      }
      else{
                  JOptionPane.showMessageDialog(
                    null,
                    "Não existe uma pessoa com este CPF",
                    "Erro de Alteração",
                    0
                );
               
      }
      limpar();
    }
     
   public void consMedCpf(){
      med = new Medico();
      
      try{
          med.setCpf(cxCpf.getText());
      } catch(CpfTamanhoException cte){
          JOptionPane.showMessageDialog(null, "CPF deve ter 11 números!", "Erro!", 0);
      }
    
      med = bdMed.consMedCod(med);    

       
      if(med != null){
        cxNome.setText(med.getNome());
        cxCpf.setText(med.getCpf());
        cxSexo.setText(Character.toString(med.getSexo()));
        cxRg.setText(med.getRg());
        cxDiaNasc.setText(Integer.toString(med.getDataNasc().getDia()));
        cxMesNasc.setText(Integer.toString(med.getDataNasc().getMes()));
        cxAnoNasc.setText(Integer.toString(med.getDataNasc().getAno()));
        cxRua.setText(med.getEnd().getNome());
        cxNumCasa.setText(Integer.toString(med.getEnd().getNum()));
        cxCompl.setText(med.getEnd().getCompl());
        cxBairro.setText(med.getEnd().getBairro());
        cxEstado.setText(med.getEnd().getEstado());
        cxCidade.setText(med.getEnd().getCidade());
        cxPais.setText(med.getEnd().getPais());
        cxCep.setText(Integer.toString(med.getEnd().getCep()));
        cxDdd.setText(Integer.toString(med.getTel().getDdd()));
        cxTel.setText(Integer.toString(med.getTel().getTel()));
        cxCtps.setText(Integer.toString(med.getCtps()));
        cxSalario.setText(Float.toString(med.getSalario()));
        cxCrmNum.setText(Integer.toString(med.getCrm().getNum()));
        cxCrmEstado.setText(med.getCrm().getEstado());
        cxEspec.setText(med.getEspec());
        cxEmail.setText(med.getEmail());
      }
      else{
                  JOptionPane.showMessageDialog(
                    null,
                    "Não existe uma pessoa com este CPF",
                    "Erro de Consulta",
                    0
                );
                limpar();
      }
        
    }
   
    public void reajusta(){
      med = new Medico();
      
      try{
          med.setCpf(cxCpf.getText());
      } catch(CpfTamanhoException cte){
          JOptionPane.showMessageDialog(null, "CPF deve ter 11 números!", "Erro!", 0);
      }
    
      med = bdMed.reajustaMed(med);    

      consMedCpf();
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reajusta;
    private javax.swing.JButton Relatório;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxAnoNasc;
    private javax.swing.JTextField cxBairro;
    private javax.swing.JTextField cxCep;
    private javax.swing.JTextField cxCidade;
    private javax.swing.JTextField cxCompl;
    private javax.swing.JTextField cxCpf;
    private javax.swing.JTextField cxCrmEstado;
    private javax.swing.JTextField cxCrmNum;
    private javax.swing.JTextField cxCtps;
    private javax.swing.JTextField cxDdd;
    private javax.swing.JTextField cxDiaNasc;
    private javax.swing.JTextField cxEmail;
    private javax.swing.JTextField cxEspec;
    private javax.swing.JTextField cxEstado;
    private javax.swing.JTextField cxMesNasc;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxNumCasa;
    private javax.swing.JTextField cxPais;
    private javax.swing.JTextField cxRg;
    private javax.swing.JTextField cxRua;
    private javax.swing.JTextField cxSalario;
    private javax.swing.JTextField cxSexo;
    private javax.swing.JTextField cxTel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAnoNasc;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCep;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelCompl;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelCrmEstado;
    private javax.swing.JLabel labelCrmNum;
    private javax.swing.JLabel labelCtps;
    private javax.swing.JLabel labelDdd;
    private javax.swing.JLabel labelDiaNasc;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmprego;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelEspec;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelMedico;
    private javax.swing.JLabel labelMesNac;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumCasa;
    private javax.swing.JLabel labelPais;
    private javax.swing.JLabel labelRg;
    private javax.swing.JLabel labelRua;
    private javax.swing.JLabel labelSalario;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel labelTel;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JTable tabMed;
    // End of variables declaration//GEN-END:variables
}
