//Nome: Erick Elsas de Freitas - RA: 2347938 - Engenharia de Software
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CadPac extends javax.swing.JFrame {
    private static CadPac unicoCadPac;   
    private Paciente pac = new Paciente();
    private static BD_Pac bdPac = new BD_Pac();
    /**
     * Creates new form MenuMed
     */
    public static CadPac getCadPac(){
        if(unicoCadPac == null){
            unicoCadPac = new CadPac();
        }
        return unicoCadPac;
    }
    public CadPac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cxEstado = new javax.swing.JTextField();
        labelTel = new javax.swing.JLabel();
        cxCidade = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        cxNumCasa = new javax.swing.JTextField();
        labelEndereco = new javax.swing.JLabel();
        labelCompl = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabPac = new javax.swing.JTable();
        cxRua = new javax.swing.JTextField();
        btConsultar = new javax.swing.JButton();
        labelPais = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        cxBairro = new javax.swing.JTextField();
        cxMesNasc = new javax.swing.JTextField();
        cxCompl = new javax.swing.JTextField();
        labelPaciente = new javax.swing.JLabel();
        cxDiaNasc = new javax.swing.JTextField();
        labelDdd = new javax.swing.JLabel();
        Relatório = new javax.swing.JButton();
        cxCpf = new javax.swing.JTextField();
        cxAnoNasc = new javax.swing.JTextField();
        labelSexo = new javax.swing.JLabel();
        cxCep = new javax.swing.JTextField();
        labelCidade = new javax.swing.JLabel();
        labelRg = new javax.swing.JLabel();
        labelBairro = new javax.swing.JLabel();
        btDeletar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        labelDiaNasc = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        cxTel = new javax.swing.JTextField();
        labelTelefone = new javax.swing.JLabel();
        labelNumCasa = new javax.swing.JLabel();
        cxPais = new javax.swing.JTextField();
        cxEmail = new javax.swing.JTextField();
        cxDdd = new javax.swing.JTextField();
        labelAnoNasc = new javax.swing.JLabel();
        labelCep = new javax.swing.JLabel();
        cxSexo = new javax.swing.JTextField();
        labelMesNac = new javax.swing.JLabel();
        btAtualizar = new javax.swing.JButton();
        labelRua = new javax.swing.JLabel();
        cxRg = new javax.swing.JTextField();
        labelPront = new javax.swing.JLabel();
        cxPront = new javax.swing.JTextField();
        labelTipoSang = new javax.swing.JLabel();
        cxTipoSang = new javax.swing.JTextField();
        labelSus = new javax.swing.JLabel();
        cxSus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTel.setText("TELEFONE");

        labelEmail.setText("EMAIL");

        labelEndereco.setText("ENDEREÇO");

        labelCompl.setText("COMPLEMENTO");

        btCadastrar.setText("CADASTRAR");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btLimpar.setText("LIMPAR");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        tabPac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NOME", "CPF", "PRONTUÁRIO"
            }
        ));
        tabPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPacMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabPac);

        btConsultar.setText("CONSULTAR");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        labelPais.setText("PAÍS");

        labelCpf.setText("CPF");

        cxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeActionPerformed(evt);
            }
        });

        labelPaciente.setText("DADOS PACIENTE");

        labelDdd.setText("DDD");

        Relatório.setText("Relatório");
        Relatório.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatórioActionPerformed(evt);
            }
        });

        labelSexo.setText("SEXO");

        labelCidade.setText("CIDADE");

        labelRg.setText("RG");

        labelBairro.setText("BAIRRO");

        btDeletar.setText("DELETAR");
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });

        btSair.setText("SAIR");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        labelDiaNasc.setText("DIA NASCIMENTO");

        labelEstado.setText("ESTADO");

        labelNome.setText("NOME");

        labelTelefone.setText("TELEFONE");

        labelNumCasa.setText("NÚMERO CASA");

        labelAnoNasc.setText("ANO NASCIMENTO");

        labelCep.setText("CEP");

        labelMesNac.setText("MÊS NASCIMENTO");

        btAtualizar.setText("ATUALIZAR");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        labelRua.setText("RUA");

        labelPront.setText("PRONTUÁRIO");

        labelTipoSang.setText("TIPO SANGUINEO");

        labelSus.setText("SUS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelPront, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxPront, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(labelTipoSang, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxTipoSang, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSus, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxSus, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Relatório, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelDiaNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cxDiaNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelMesNac, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cxMesNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(labelCompl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxCompl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(labelDdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxDdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(labelTel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxTel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelRg, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxRg, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelAnoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cxAnoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(labelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelRua, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxRua, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(labelNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelPais, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(labelCep, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxCep, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(361, Short.MAX_VALUE)
                .addComponent(labelPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPront)
                    .addComponent(cxPront, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipoSang)
                    .addComponent(cxTipoSang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSus)
                    .addComponent(cxSus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCadastrar)
                            .addComponent(btAtualizar)
                            .addComponent(btLimpar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btDeletar)
                            .addComponent(btConsultar)
                            .addComponent(btSair)))
                    .addComponent(Relatório, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNome)
                        .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCpf)
                        .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelRg)
                        .addComponent(cxRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelSexo)
                        .addComponent(cxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelMesNac)
                        .addComponent(cxMesNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelDiaNasc)
                        .addComponent(cxDiaNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelAnoNasc)
                        .addComponent(cxAnoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelEmail)
                        .addComponent(cxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(labelEndereco)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelRua)
                        .addComponent(cxRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelNumCasa)
                        .addComponent(cxNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelBairro)
                        .addComponent(cxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCompl)
                        .addComponent(cxCompl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCidade)
                        .addComponent(cxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelEstado)
                        .addComponent(cxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelPais)
                        .addComponent(cxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCep)
                        .addComponent(cxCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(labelTelefone)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDdd)
                        .addComponent(cxDdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelTel)
                        .addComponent(cxTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(374, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        cadPac();
        listaTab();// TODO add your handling code here:
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();// TODO add your handling code here:
    }//GEN-LAST:event_btLimparActionPerformed

    private void tabPacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPacMouseClicked
        selectTabPac();        // TODO add your handling code here:
    }//GEN-LAST:event_tabPacMouseClicked

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consPacCpf();        // TODO add your handling code here:
    }//GEN-LAST:event_btConsultarActionPerformed

    private void cxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeActionPerformed

    private void RelatórioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatórioActionPerformed
        abrirRelatorio();// TODO add your handling code here:
    }//GEN-LAST:event_RelatórioActionPerformed

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        excluiPacCpf();
        listaTab();// TODO add your handling code here:
    }//GEN-LAST:event_btDeletarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();        // TODO add your handling code here:
    }//GEN-LAST:event_btSairActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        atualizaPacCpf();        // TODO add your handling code here:
    }//GEN-LAST:event_btAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadPac().setVisible(true);
            }
        });
    }
 
    public void abrirRelatorio(){
        RelBDPac.getRelBDPac(bdPac).setVisible(true);
    }
    
    public void selectTabPac(){
        String valLinTab = "";
        int posLin = tabPac.getSelectedRow();
          
        
        for(int coluna = 0;coluna < tabPac.getColumnCount(); coluna++ ){
            valLinTab += tabPac.getModel().getValueAt(posLin,coluna).toString();
            
            if(coluna < tabPac.getColumnCount()-1){
               valLinTab += " - ";
            }
            
            
        }
        JOptionPane.showMessageDialog(
                null,
                "Valor escolhido: "+ valLinTab,
                "Seleção na tabela",
                1
        );
    }
        
    public void listaTab(){
        DefaultTableModel modelo = (DefaultTableModel) tabPac.getModel();
        
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for(Paciente pac : bdPac.getBdPac() ){
            modelo.insertRow(posLin, new Object[]{pac.getNome(), pac.getCpf(), pac.getPront()});
            posLin++;
        }
    }
        
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                    null,
                    "Deseja sair?",
                    "Saida",
                    JOptionPane.YES_NO_OPTION
                  );
        if(resp == 0){
            dispose();
        }
    }

    public void limpar(){
        cxNome.setText("");
        cxCpf.setText("");
        cxSexo.setText("");
        cxRg.setText("");
        cxDiaNasc.setText("");
        cxMesNasc.setText("");
        cxAnoNasc.setText("");
        cxRua.setText("");
        cxNumCasa.setText("");
        cxCompl.setText("");
        cxBairro.setText("");
        cxEstado.setText("");
        cxCidade.setText("");
        cxPais.setText("");
        cxCep.setText("");
        cxDdd.setText("");
        cxTel.setText("");
        cxTipoSang.setText("");
        cxPront.setText("");
        cxSus.setText("");
        cxEmail.setText("");
        cxNome.requestFocus();
    }
    
    public void cadPac(){
       pac = new Paciente();
       int flag = 1;
       
       try{
           pac.setCpf(cxCpf.getText());
           pac.setNome(cxNome.getText());
           pac.setSexo(cxSexo.getText().charAt(0));
           pac.setRg(cxRg.getText());
           pac.setEmail(cxEmail.getText());
           pac.getDataNasc().setDia(Integer.parseInt(cxDiaNasc.getText()));
           pac.getDataNasc().setMes(Integer.parseInt(cxMesNasc.getText()));
           pac.getDataNasc().setAno(Integer.parseInt(cxAnoNasc.getText()));
           pac.getEnd().setNome(cxRua.getText());
           pac.getEnd().setNum(Integer.parseInt(cxNumCasa.getText()));
           pac.getEnd().setBairro(cxBairro.getText());
           pac.getEnd().setCompl(cxCompl.getText());
           pac.getEnd().setCidade(cxCidade.getText());
           pac.getEnd().setEstado(cxEstado.getText());
           pac.getEnd().setPais(cxPais.getText());
           pac.getEnd().setCep(Integer.parseInt(cxCep.getText()));
           pac.getTel().setDdd(Integer.parseInt(cxDdd.getText()));
           pac.getTel().setTel(Integer.parseInt(cxTel.getText()));
           pac.setPront(Integer.parseInt(cxPront.getText()));
           pac.setSus(Integer.parseInt(cxSus.getText()));
           pac.setTipoSang(cxTipoSang.getText());
           flag = 0;
       } catch (CpfTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "CPF deve ter 11 números!", "Erro!", 0);
        } catch (SexoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, "Sexo deve ser F ou M!", "Erro!", 0);
        } catch (RgTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "RG deve ter 9 números!!", "Erro!", 0);
        } catch (DiaInvalidoException ex) {
            JOptionPane.showMessageDialog(null, "Dia deve ser um valor entre 1 e 31!", "Erro!", 0);
        } catch (MesInvalidoException ex) {
            JOptionPane.showMessageDialog(null, "Mês deve ser um valor entre 1 e 12!", "Erro!", 0);
        } catch (AnoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, "Ano deve ser um valor entre 1900 e 2022", "Erro!", 0);
        } catch (NumNegException ex) {
            JOptionPane.showMessageDialog(null, "Rua deve ter um valor positivo!", "Erro!", 0);
        } catch (EstadoTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "Estado deve ter dois caracteres!", "Erro!", 0);
        } catch (EstadoCaracterException ex) {
            JOptionPane.showMessageDialog(null, "Estado deve ser composto por letras!", "Erro!", 0);
        } catch (CepTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "CEP deve ter 9 números!", "Erro!", 0);
        } catch (DddTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "DDD deve ter 2 números!", "Erro!", 0);
        } catch (TelefoneTamanhoException ex) {
            JOptionPane.showMessageDialog(null, "Telefone deve ter 9 números!", "Erro!", 0);
        } catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Data de Nascimento, número da rua, CEP, CTPS ou CRM devem ser compostos por números", "Erro!", 0);
        } catch (TipoSangInvalidoException ex) {
            JOptionPane.showMessageDialog(null, "Tipo Sanguineo deve ser composto por A, B, O ou AB seguido por um + ou -", "Erro!", 0);
        }
       
       if(flag == 0){
           pac = bdPac.cadPac(pac);
       } else {
           JOptionPane.showMessageDialog(null,
                   "Erro durante cadastro! Tente Novamente",
                   "Erro de cadastro", 0);
           return;
       }

       if(pac != null){
                JOptionPane.showMessageDialog(
                    null,
                    "Paciente cadastrado com sucesso!",
                    "Cadastro Ok",
                    1
                );
                limpar();
       }
       else{
                JOptionPane.showMessageDialog(
                    null,
                    "Já existe uma pessoa com este CPF ou CRM",
                    "Erro de Cadastro",
                    0
                );
                limpar();
       }
    }
       
    public void excluiPacCpf(){
      pac = new Paciente();
      
      try{
          pac.setCpf(cxCpf.getText());
      } catch(CpfTamanhoException cte){
          JOptionPane.showMessageDialog(null, "CPF deve ter 11 números!", "Erro!", 0);
      }
      
      pac = bdPac.removePacCod(pac);
       
      if(pac == null){
            JOptionPane.showMessageDialog(
                    null,
                    "Pessoa EXCLUÍDA com sucesso!",
                    "Exclusão OK",
                    1
                );
      }
      else{
                  JOptionPane.showMessageDialog(
                    null,
                    "Não existe uma pessoa com este CPF",
                    "Erro de Excluasão",
                    0
                );
               
      }
      limpar();
    }
    
     public void atualizaPacCpf(){
      pac = new Paciente();
      
      try{
          pac.setCpf(cxCpf.getText());
      } catch(CpfTamanhoException cte){
          JOptionPane.showMessageDialog(null, "CPF deve ter 11 números!", "Erro!", 0);
      }
      
      pac = bdPac.atualizaPacCod(pac);    
       
      if(pac != null){
        cxNome.setText(pac.getNome());
        cxCpf.setText(pac.getCpf());
        cxSexo.setText(Character.toString(pac.getSexo()));
        cxRg.setText(pac.getRg());
        cxDiaNasc.setText(Integer.toString(pac.getDataNasc().getDia()));
        cxMesNasc.setText(Integer.toString(pac.getDataNasc().getMes()));
        cxAnoNasc.setText(Integer.toString(pac.getDataNasc().getAno()));
        cxRua.setText(pac.getEnd().getNome());
        cxNumCasa.setText(Integer.toString(pac.getEnd().getNum()));
        cxCompl.setText(pac.getEnd().getCompl());
        cxBairro.setText(pac.getEnd().getBairro());
        cxEstado.setText(pac.getEnd().getEstado());
        cxCidade.setText(pac.getEnd().getCidade());
        cxPais.setText(pac.getEnd().getPais());
        cxCep.setText(Integer.toString(pac.getEnd().getCep()));
        cxDdd.setText(Integer.toString(pac.getTel().getDdd()));
        cxTel.setText(Integer.toString(pac.getTel().getTel()));
        cxPront.setText(Integer.toString(pac.getPront()));
        cxSus.setText(Integer.toString(pac.getSus()));
                JOptionPane.showMessageDialog(
                    null,
                    "Pessoa atualizada com sucesso!",
                    "Atualização OK",
                    1
                );
      }
      else{
                  JOptionPane.showMessageDialog(
                    null,
                    "Não existe uma pessoa com este CPF",
                    "Erro de Alteração",
                    0
                );
               
      }
      limpar();
    }
     
   public void consPacCpf(){
      pac = new Paciente();
      
      try{
          pac.setCpf(cxCpf.getText());
      } catch(CpfTamanhoException cte){
          JOptionPane.showMessageDialog(null, "CPF deve ter 11 números!", "Erro!", 0);
      }
    
      pac = bdPac.consPacCod(pac);    

       
      if(pac != null){
        cxNome.setText(pac.getNome());
        cxCpf.setText(pac.getCpf());
        cxSexo.setText(Character.toString(pac.getSexo()));
        cxRg.setText(pac.getRg());
        cxDiaNasc.setText(Integer.toString(pac.getDataNasc().getDia()));
        cxMesNasc.setText(Integer.toString(pac.getDataNasc().getMes()));
        cxAnoNasc.setText(Integer.toString(pac.getDataNasc().getAno()));
        cxRua.setText(pac.getEnd().getNome());
        cxNumCasa.setText(Integer.toString(pac.getEnd().getNum()));
        cxCompl.setText(pac.getEnd().getCompl());
        cxBairro.setText(pac.getEnd().getBairro());
        cxEstado.setText(pac.getEnd().getEstado());
        cxCidade.setText(pac.getEnd().getCidade());
        cxPais.setText(pac.getEnd().getPais());
        cxCep.setText(Integer.toString(pac.getEnd().getCep()));
        cxDdd.setText(Integer.toString(pac.getTel().getDdd()));
        cxTel.setText(Integer.toString(pac.getTel().getTel()));
        cxPront.setText(Integer.toString(pac.getPront()));
        cxSus.setText(Integer.toString(pac.getSus()));
        cxTipoSang.setText(pac.getTipoSang());
        cxEmail.setText(pac.getEmail());
      }
      else{
                  JOptionPane.showMessageDialog(
                    null,
                    "Não existe uma pessoa com este CPF",
                    "Erro de Consulta",
                    0
                );
                limpar();
      }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Relatório;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxAnoNasc;
    private javax.swing.JTextField cxBairro;
    private javax.swing.JTextField cxCep;
    private javax.swing.JTextField cxCidade;
    private javax.swing.JTextField cxCompl;
    private javax.swing.JTextField cxCpf;
    private javax.swing.JTextField cxDdd;
    private javax.swing.JTextField cxDiaNasc;
    private javax.swing.JTextField cxEmail;
    private javax.swing.JTextField cxEstado;
    private javax.swing.JTextField cxMesNasc;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxNumCasa;
    private javax.swing.JTextField cxPais;
    private javax.swing.JTextField cxPront;
    private javax.swing.JTextField cxRg;
    private javax.swing.JTextField cxRua;
    private javax.swing.JTextField cxSexo;
    private javax.swing.JTextField cxSus;
    private javax.swing.JTextField cxTel;
    private javax.swing.JTextField cxTipoSang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAnoNasc;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCep;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelCompl;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelDdd;
    private javax.swing.JLabel labelDiaNasc;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelMesNac;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumCasa;
    private javax.swing.JLabel labelPaciente;
    private javax.swing.JLabel labelPais;
    private javax.swing.JLabel labelPront;
    private javax.swing.JLabel labelRg;
    private javax.swing.JLabel labelRua;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel labelSus;
    private javax.swing.JLabel labelTel;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTipoSang;
    private javax.swing.JTable tabPac;
    // End of variables declaration//GEN-END:variables
}
