//Nome: Erick Elsas de Freitas - RA: 2347938 - Engenharia de Software
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class RelBDMed extends javax.swing.JFrame {

        private Medico med = new Medico();
        private static RelBDMed unicoBDMed;
        private static BD_Med bdMed;
        
   public static RelBDMed getRelBDMed(BD_Med bdMed1){
        bdMed = bdMed1;
        if(unicoBDMed == null){
            unicoBDMed = new RelBDMed();
        }
        return unicoBDMed;
    }
  
    private RelBDMed() {
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabMed = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        tabMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NOME", "RG", "CPF", "RUA", "NÚMERO CASA", "BAIRRO", "CIDADE", "ESTADO", "PAÍS", "CEP", "DDD", "TELEFONE", "EMAIL", "SEXO", "DIA NASC", "MES NASC", "ANO NASC", "SALARIO", "CTPS", "CRM NUM", "ESPECIALIZAÇÃO"
            }
        ));
        tabMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMedMouseClicked(evt);
            }
        });
        tabMed.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabMedPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tabMed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1741, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMedMouseClicked
        selectTabMed();        // TODO add your handling code here:
    }//GEN-LAST:event_tabMedMouseClicked

    private void tabMedPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabMedPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tabMedPropertyChange

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        listaTab();        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    /**
     * @param args the command line arguments
     */
          public void selectTabMed(){
        String valLinTab = "";
        int posLin = tabMed.getSelectedRow();
          
        
        for(int coluna = 0;coluna < tabMed.getColumnCount(); coluna++ ){
            valLinTab += tabMed.getModel().getValueAt(posLin,coluna).toString();
            
            if(coluna < tabMed.getColumnCount()-1){
               valLinTab += " - ";
            }
            
        }
        JOptionPane.showMessageDialog(
                null,
                "Valor escolhido: "+valLinTab,
                "Seleção na tabela",
                1
        );
    }
    public void listaTab(){
        DefaultTableModel modelo = (DefaultTableModel) tabMed.getModel();
        
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for(Medico med : bdMed.getBdMed() ){
            modelo.insertRow(posLin, new Object[]{med.getNome(), med.getRg(), med.getCpf(), med.getEnd().getNome(), 
                med.getEnd().getNum(), med.getEnd().getBairro(), med.getEnd().getCidade(), med.getEnd().getEstado(),
                med.getEnd().getPais(), med.getEnd().getCep(), med.getTel().getDdd(), med.getTel().getTel(), med.getEmail(),
                med.getSexo(), med.getDataNasc().getDia(), med.getDataNasc().getMes(), med.getDataNasc().getAno(), med.getSalario(), med.getCtps(), 
                med.getCrm().getNum(), med.getEspec()});
            posLin++;
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelBDMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelBDMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelBDMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelBDMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelBDMed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabMed;
    // End of variables declaration//GEN-END:variables
}
