//Nome: Erick Elsas de Freitas - RA: 2347938 - Engenharia de Software
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class RelBDPac extends javax.swing.JFrame {

        private Paciente pac = new Paciente();
        private static RelBDPac unicoBDPac;
        private static BD_Pac bdPac;
        
   public static RelBDPac getRelBDPac(BD_Pac bdPac1){
        bdPac = bdPac1;
        if(unicoBDPac == null){
            unicoBDPac= new RelBDPac();
        }
        return unicoBDPac;
    }
  
    public RelBDPac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        tabPac = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        tabPac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NOME", "RG", "CPF", "RUA", "NÚMERO CASA", "BAIRRO", "CIDADE", "ESTADO", "PAÍS", "CEP", "DDD", "TELEFONE", "EMAIL", "SEXO", "DIA NASC", "MES NASC", "ANO NASC", "PRONTUÁRIO", "SUS", "TIPO SANG"
            }
        ));
        tabPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPacMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabPac);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1339, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabPacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPacMouseClicked
        selectTabPac();        // TODO add your handling code here:
    }//GEN-LAST:event_tabPacMouseClicked

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        listaTab();        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    public void selectTabPac(){
        String valLinTab = "";
        int posLin = tabPac.getSelectedRow();
          
        
        for(int coluna = 0;coluna < tabPac.getColumnCount(); coluna++ ){
            valLinTab += tabPac.getModel().getValueAt(posLin,coluna).toString();
            
            if(coluna < tabPac.getColumnCount()-1){
               valLinTab += " - ";
            }
            
        }
        JOptionPane.showMessageDialog(
                null,
                "Valor escolhido: "+valLinTab,
                "Seleção na tabela",
                1
        );
    }
    public void listaTab(){
        DefaultTableModel modelo = (DefaultTableModel) tabPac.getModel();
        
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for(Paciente pac : bdPac.getBdPac() ){
            modelo.insertRow(posLin, new Object[]{pac.getNome(), pac.getRg(), pac.getCpf(), pac.getEnd().getNome(), 
                pac.getEnd().getNum(), pac.getEnd().getBairro(), pac.getEnd().getCidade(), pac.getEnd().getEstado(),
                pac.getEnd().getPais(), pac.getEnd().getCep(), pac.getTel().getDdd(), pac.getTel().getTel(), pac.getEmail(),
                pac.getSexo(), pac.getDataNasc().getDia(), pac.getDataNasc().getMes(), pac.getDataNasc().getAno(), pac.getPront(),
                pac.getSus(), pac.getTipoSang()});
            posLin++;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelBDPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelBDPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelBDPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelBDPac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelBDPac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tabPac;
    // End of variables declaration//GEN-END:variables
}
