//Nome: Erick Elsas de Freitas - RA: 2347938 - Engenharia de Software
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class RelBDEnf extends javax.swing.JFrame {

        private Enfermeiro enf = new Enfermeiro();
        private static RelBDEnf unicoBDEnf;
        private static BD_Enf bdEnf;
        
   public static RelBDEnf getRelBDEnf(BD_Enf bdEnf1){
        bdEnf = bdEnf1;
        if(unicoBDEnf == null){
            unicoBDEnf = new RelBDEnf();
        }
        return unicoBDEnf;
    }
   
    public RelBDEnf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabEnf = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        tabEnf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NOME", "RG", "CPF", "RUA", "NÚMERO CASA", "BAIRRO", "CIDADE", "ESTADO", "PAÍS", "CEP", "DDD", "TELEFONE", "EMAIL", "SEXO", "DIA NASC", "MES NASC", "ANO NASC", "SALARIO", "CTPS", "GRAU FORM", "SETOR HOSP"
            }
        ));
        tabEnf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabEnfMouseClicked(evt);
            }
        });
        tabEnf.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabEnfPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tabEnf);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabEnfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabEnfMouseClicked
        selectTabEnf();        // TODO add your handling code here:
    }//GEN-LAST:event_tabEnfMouseClicked

    private void tabEnfPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabEnfPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tabEnfPropertyChange

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        listaTab();        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    /**
     * @param args the command line arguments
     */
    public void selectTabEnf(){
        String valLinTab = "";
        int posLin = tabEnf.getSelectedRow();
          
        
        for(int coluna = 0;coluna < tabEnf.getColumnCount(); coluna++ ){
            valLinTab += tabEnf.getModel().getValueAt(posLin,coluna).toString();
            
            if(coluna < tabEnf.getColumnCount()-1){
               valLinTab += " - ";
            }
            
        }
        JOptionPane.showMessageDialog(
                null,
                "Valor escolhido: "+valLinTab,
                "Seleção na tabela",
                1
        );
    }
    public void listaTab(){
        DefaultTableModel modelo = (DefaultTableModel) tabEnf.getModel();
        
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for(Enfermeiro enf : bdEnf.getBdEnf() ){
            modelo.insertRow(posLin, new Object[]{enf.getNome(), enf.getRg(), enf.getCpf(), enf.getEnd().getNome(), 
                enf.getEnd().getNum(), enf.getEnd().getBairro(), enf.getEnd().getCidade(), enf.getEnd().getEstado(),
                enf.getEnd().getPais(), enf.getEnd().getCep(), enf.getTel().getDdd(), enf.getTel().getTel(), enf.getEmail(),
                enf.getSexo(), enf.getDataNasc().getDia(), enf.getDataNasc().getMes(), enf.getDataNasc().getAno(), enf.getSalario(), enf.getCtps(), 
                enf.getGrauForm(), enf.getSetorHosp()});
            posLin++;
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelBDEnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelBDEnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelBDEnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelBDEnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelBDEnf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabEnf;
    // End of variables declaration//GEN-END:variables
}
